#################################################################
## Notify Washer
#
## Notify Smartphones when washer is complete.
#################################################################
id: 1f617fc8-fb8d-4145-bf88-f5fed64b64cc
alias: Notify Washer
description: Notify smartphones when washer is complete.
trigger:
  - platform: state
    entity_id: sensor.washer
    attribute: run_completed
    from: "off"
    to: "on"
condition: []
action:
  - service: notify.smartphones
    data:
      title: 🧺 Laundry Complete!
      message: Time to empty the washer.
  # Turn off washer
  - type: turn_off
    device_id: ef6deb28b5c011bcd5ccaa5dbf8a0c75
    entity_id: 825bb0722fb6e54803496233f0ba8325
    domain: switch
mode: single
