#################################################################
## Notify Vacuum Maintenance
#
## Notify smartphones when Winston needs maintenance.
#################################################################
alias: Notify Vacuum Maintenance
description: "Notify smartphones when Winston needs maintenance."
trigger:
  - platform: state
    entity_id: vacuum.winston
    from: cleaning
    to: returning
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.vacuum_sensors
            below: "10"
        sequence:
          - service: notify.smartphones
            data:
              title: 🔧Tune-up Winston
              message: Clean Winston's sensors.
      - conditions:
          - condition: numeric_state
            entity_id: sensor.vacuum_filter
            below: "10"
        sequence:
          - service: notify.smartphones
            data:
              title: 🔧Tune-up Winston
              message: Change Winston's filter.
      - conditions:
          - condition: numeric_state
            entity_id: sensor.vacuum_mainbrush
            below: "10"
        sequence:
          - service: notify.smartphones
            data:
              title: 🔧Tune-up Winston
              message: Clean Winston's mainbrush.
      - conditions:
          - condition: numeric_state
            entity_id: sensor.vacuum_sidebrush
            below: "10"
        sequence:
          - service: notify.smartphones
            data:
              title: 🔧Tune-up Winston
              message: Change Winston's sidebrush.
    default: []
mode: single
