#################################################################
## Notify Printer
#
## Notify Smartphones when Major Laser Printer is ready.
#################################################################
id: b8231205-ebc7-4c83-9583-b55fa1df0767
alias: Notify Printer
description: Notify Smartphones when Major Laser Printer is ready.
trigger:
  - platform: state
    entity_id: sensor.major_laser_printer
    from: unavailable
    to: idle
action:
  - service: notify.smartphones
    data:
      message: Ready to print.
      title: "🖨️ Major Laser Printer:"
mode: single
