#################################################################
## This handles the loading of my binary sensors.
#################################################################
binary_sensor:
  - platform: mqtt
    name: Hallway Mqtt Room
    state_topic: !secret presense_hallway_state_topic # use the MQTT topic for the room
    json_attributes_topic: !secret presense_hallway_telemetry
    payload_on: online
    payload_off: offline
    device_class: connectivity
  - platform: mqtt
    name: Living Room Mqtt Room
    state_topic: !secret presense_living_room_state_topic # use the MQTT topic for the room
    json_attributes_topic: !secret presense_living_room_telemetry
    payload_on: online
    payload_off: offline
    device_class: connectivity
  - platform: mqtt
    name: Office Mqtt Room
    state_topic: !secret presense_office_state_topic # use the MQTT topic for the room
    json_attributes_topic: !secret presense_office_telemetry
    payload_on: online
    payload_off: offline
    device_class: connectivity
