#################################################################
## This handles the loading of my customizations.
#################################################################
homeassistant:
  # Lets me customize individual entities
  customize: !include ../includes/customize.yaml