#################################################################
## Base Button Properties
#################################################################
  aspect_ratio: 1/1
  show_state: true
  show_icon: false
  variables:
    state: >
      [[[ return entity === undefined || entity.state; ]]]
    timeout: >
      [[[ return entity === undefined || Date.now() - Date.parse(entity.last_changed); ]]]
    light_color: >
      [[[ return entity === undefined ? 'var(--state-icon-color)' : 'var(--button-card-light-color-no-temperature)'; ]]]
  state:
    - value: "on"
      styles:
        card: [background-color: "rgba(255, 255, 255, 0.8)"]
        name: [color: "rgba(0, 0, 0, 0.6)"]
        state: [color: "rgba(0, 0, 0, 0.6)"]
  tap_action:
    action: toggle
    haptic: light
  hold_action:
    action: none
  double_tap_action:
    haptic: selection
  styles:
    name: [top: 57.7%, left: 11%, line-height: 2em, position: absolute]
    state: [top: 74%, left: 11%, line-height: 2em, position: absolute]
    card:
      [
        font-family: Sf Display,
        letter-spacing: 0.05em,
        font-weight: 400,
        color: "rgba(255, 255, 255, 0.3)",
        font-size: 1em,
        background-color: "rgba(115, 115, 115, 0.2)",
        border-radius: 2em,
        box-shadow: none,
        transition: none,
      ]
