#################################################################
## Shutdown Shredder
#
## Shutoff plug to paper shredder 2-minutes after device has been switched on.
#################################################################
id: 36a89bf0-c131-4f9c-90d6-971e9c321ef1
alias: Shutoff Shredder
description:
  Shutoff plug to paper shredder 2-minutes after device has been switched
  on.
trigger:
  - platform: state
    entity_id: switch.paper_shredder
    for: 00:02:00
    from: "off"
    to: "on"
action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.paper_shredder
mode: single
