set_fan_mode:
  name: Set fan mode
  description: Set fan operation for frigidaire appliance.
  target:
    entity:
      integration: frigidaire
  fields:
    fan_mode:
      name: Fan mode
      description: New value of fan mode.
      required: true
      example: "low"
      selector:
        text: