#################################################################
## Climate: Purifier
#
# Trigger 'Kirby + Airmax: Daymode' @ 8 am + 'Kirby + Airmax:
# Nighttime' @ 11 pm."
#################################################################
alias: "Climate: Purifier"
description: "Trigger 'Kirby + Airmax: Daymode' @ 8 am + 'Kirby + Airmax: Nighttime' @ 11 pm."
trigger:
  - platform: time
    at: "08:15:00"
  - platform: time
    at: "23:00:00"
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: time
                after: "23:00:00"
                before: "08:15:00"
        sequence:
          - scene: scene.kirby_nightmode
          - service: script.airmax_nightmode
    default:
      - service: fan.turn_off
        target:
          entity_id:
            - fan.kirby
      - service: script.airmax_daymode
mode: single
