#################################################################
## Climate: Purifier
#
# Trigger 'Kirby + Airmega: Daymode' @ 8 am + 'Kirby + Airmega:
# Nighttime' @ 11 pm."
#################################################################
alias: "Climate: Purifier"
description: "Trigger 'Kirby + Airmega: Daymode' @ 8 am + 'Kirby + Airmega: Nighttime' @ 11 pm."
trigger:
  - platform: time
    at: input_datetime.purifier_morning
  - platform: time
    at: input_datetime.purifier_night
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.purifier_schedule
            state: "on"
        sequence:
          - scene: scene.kirby_nightmode
          - service: fan.turn_off
            target:
              entity_id:
                - fan.kitchen
          - service: script.airmega_nightmode
    default:
      - service: fan.turn_off
        target:
          entity_id:
            - fan.kirby
      - service: script.airmega_daymode
mode: single
