#################################################################
## Climate: Office Off
#
## Turn fan OFF based off of Overhead light group.
#################################################################
id: 6f1b1dd9-bfe4-48c2-ae62-a07257061ffa
alias: "Climate: Office Off"
description: "Turn fan OFF based off of Overhead light group."
trigger:
  - platform: state
    entity_id: light.overhead
    from: "on"
    to: "off"
action:
  - type: turn_off
    device_id: 81424ac53e80a7fdde726394ebea9ca2
    entity_id: switch.mini_air_circulator
    domain: switch
mode: single
