#################################################################
## Climate: AQI
#
# Trigger 'Kirby + Airmax: Daymode' @ 8 am + 'Kirby + Airmax:
# Nighttime' @ 9 pm."
#################################################################
alias: "Climate: AQI"
description: "Trigger 'Kirby + Airmax: Daymode' @ 8 am + 'Kirby + Airmax: Nighttime' @ 9 pm."
trigger:
  - platform: time
    at: "08:15:00"
  - platform: time
    at: "21:00:00"
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: time
                after: "21:00:00"
                before: "08:15:00"
        sequence:
          - scene: scene.kirby_nightmode
          - service: script.airmax_nightmode
    default:
      - scene: scene.kirby_daymode
      - service: script.airmax_daymode
mode: single
