#################################################################
## Climate: Loft
#
## Turn on fan when Loft is ≥72° and off when ≤71°.
#################################################################
id: 39e8f061-3095-43cd-9ca9-e1308ab872c1
alias: "Climate: Loft"
description: "Turn on fan when Loft is ≥72° and off when ≤71°."
trigger:
  - type: temperature
    platform: device
    device_id: a9f869ec3d4b012b2455783c52a43eba
    entity_id: sensor.kirby_temperature
    domain: sensor
    above: 72
  - type: temperature
    platform: device
    device_id: a9f869ec3d4b012b2455783c52a43eba
    entity_id: sensor.kirby_temperature
    domain: sensor
    below: 71
action:
  - choose:
      - conditions:
          - type: is_temperature
            condition: device
            device_id: a9f869ec3d4b012b2455783c52a43eba
            entity_id: sensor.kirby_temperature
            domain: sensor
            above: 72
        sequence:
          - service: fan.turn_om
            target:
              entity_id: fan.air_circulator
    default:
      - service: fan.turn_off
        target:
          entity_id: fan.air_circulator
mode: single
