#################################################################
## Alert Leak
#
## Alert when water is detected under the sink.
#################################################################
alias: Alert Leak
description: Alert when water is detected under the sink.
trigger:
  - type: moist
    platform: device
    device_id: 6bd7ff509b62f7b1c7fbd08263ceb018
    entity_id: binary_sensor.water
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
condition: []
action:
  - service: notify.smartphones
    data:
      message: Leak in kitchen!
      title: "🚨 ALERT:"
mode: single
