#################################################################
## Climate: Kirby
#
## Trigger 'Kirby: Daytime' @ 8 am + 'Kirby: Nighttime' @ 9 pm.
#################################################################
alias: "Climate: Kirby"
description: "Trigger 'Kirby: Daytime' @ 8 am + 'Kirby: Nighttime' @ 9 pm."
trigger:
  - platform: time
    at: "08:15:00"
  - platform: time
    at: "21:00:00"
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: time
                after: "21:00:00"
                before: "08:15:00"
        sequence:
          - scene: scene.kirby_nightmode
    default:
      - scene: scene.kirby_daymode
mode: single
