#################################################################
## Climate: Office On
#
## Turn fan ON based off of Overhead light group.
#################################################################
alias: "Climate: Office On"
description: "Turn fan ON based on of Overhead light group."
trigger:
  - platform: state
    entity_id: light.overhead
    to: "on"
    from: "off"
action:
  - type: turn_on
    entity_id: switch.mini_air_circulator
    domain: switch
mode: single
