#################################################################
## Climate: Office Off
#
## Turn fan OFF based off of Overhead light group.
#################################################################
alias: "Climate: Office Off"
description: "Turn fan OFF based off of Overhead light group."
trigger:
  - platform: state
    entity_id: light.overhead
    from: "on"
    to: "off"
action:
  - type: turn_off
    entity_id: switch.mini_air_circulator
    domain: switch
mode: single
