#################################################################
## Theater Mode
#
## Theater lights + quick select.
#################################################################
alias: Mode Theater
description: "Theater lights + quick select."
trigger: []
condition: []
action:
  - scene: scene.theater
  - service: script.av_quick_3
    data: {}
mode: single
