#################################################################
## Theater Mode
#
## Theater lights + quick select.
#################################################################
id: f0c874ac-ec8b-411c-aea5-9d00bfe9f88e
alias: Mode Theater
description: "Theater lights + quick select."
trigger: []
condition: []
action:
  - scene: scene.theater
  - service: script.av_quick_3
    data: {}
mode: single
