#################################################################
## Notification Printer
#
## Notify Smartphones when Major Laser Printer is ready.
#################################################################
alias: Notification Printer
description: Notify Smartphones when Major Laser Printer is ready.
trigger:
  - platform: state
    entity_id: sensor.hp_laserjet_m14_m17
    from: unavailable
    to: idle
action:
  - service: notify.smartphones
    data:
      message: Ready to print.
      title: "🖨️ Major Laser Printer:"
mode: single
