#################################################################
## Notify Washer
#
## Notify Smartphones when washer is complete.
#################################################################
alias: Notify Washer
description: Notify smartphones when washer is complete.
trigger:
  - platform: state
    entity_id: sensor.washer
    attribute: run_completed
    from: 'off'
    to: 'on'
condition: []
action:
  - service: notify.smartphones
    data:
      title: 🧺 Laundry Complete!
      message: Time to empty the washer.
mode: single
