#################################################################
## Notify Laundry
#
## Notify Smartphones when washer or dryer are complete.
#################################################################
alias: Notify Laundry
description: Notify smartphones when laundry is complete.
trigger:
  - platform: state
    entity_id: sensor.washer
    attribute: run_completed
    from: "off"
    to: "on"
  - platform: state
    entity_id: sensor.dryer
    attribute: run_completed
    from: "off"
    to: "on"
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: sensor.washer
                attribute: run_completed
                state: "on"
        sequence:
          - service: notify.smartphones
            data:
              title: 🧺 Laundry Complete!
              message: Time to empty the washer.
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: sensor.dryer
                attribute: run_completed
                state: "on"
        sequence:
          - service: notify.smartphones
            data:
              title: 🧺 Laundry Complete!
              message: Time to empty the dryer.
    default: []
mode: single
