#################################################################
## On Air
#
## Turn Potter light red when webcam turns on.
#################################################################
alias: On Air
description: "Turn Potter light red when webcam turns on."
trigger:
  - platform: state
    entity_id: binary_sensor.work_camera_in_use
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.work_camera_in_use
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: sensor.work_displays
    state: '2'
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.work_camera_in_use
            state: 'on'
            for:
              hours: 0
              minutes: 0
              seconds: 1
        sequence:
          - scene: scene.meeting
      - conditions:
          - condition: state
            entity_id: binary_sensor.work_camera_in_use
            state: 'off'
            for:
              hours: 0
              minutes: 0
              seconds: 1
        sequence:
          - scene: scene.office_available
    default: []
mode: single
