#################################################################
## On Air
#
## Turn Potter light red when webcam turns on.
#################################################################
alias: On Air
description: "Turn Potter light red when webcam turns on."
trigger:
  - type: turned_on
    platform: device
    device_id: 0d90cb630ecad3945965440c0dabc6cf
    entity_id: binary_sensor.lilt_macbook_pro_camera_in_use
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: turned_on
    platform: device
    device_id: ec19a58bbc0287067cd031a9b536f33c
    entity_id: binary_sensor.macintoshbook_air_camera_in_use
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: turned_off
    platform: device
    device_id: 0d90cb630ecad3945965440c0dabc6cf
    entity_id: binary_sensor.lilt_macbook_pro_camera_in_use
    domain: binary_sensor
  - type: turned_off
    platform: device
    device_id: ec19a58bbc0287067cd031a9b536f33c
    entity_id: binary_sensor.macintoshbook_air_camera_in_use
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - type: is_on
                condition: device
                device_id: 0d90cb630ecad3945965440c0dabc6cf
                entity_id: binary_sensor.lilt_macbook_pro_camera_in_use
                domain: binary_sensor
                for:
                  hours: 0
                  minutes: 0
                  seconds: 1
                  milliseconds: 0
        sequence:
          - scene: scene.meeting
      - conditions:
          - condition: and
            conditions:
              - type: is_on
                condition: device
                device_id: ec19a58bbc0287067cd031a9b536f33c
                entity_id: binary_sensor.macintoshbook_air_camera_in_use
                domain: binary_sensor
                for:
                  hours: 0
                  minutes: 0
                  seconds: 1
                  milliseconds: 0
        sequence:
          - scene: scene.meeting
    default:
      - scene: scene.office_available
mode: single
