#################################################################
## Peak Usage Alerts
#
## Notify Smartphones when AC, Washer, or Dryer is on during peak usage.
#################################################################
id: 3b332e5e-c742-46ff-a002-d0f2fb23aeda
alias: "Peak Usage Alerts"
description: "Notify Smartphones when AC, Washer, or Dryer is on during peak usage."
trigger:
  - platform: state
    entity_id: climate.ice_bear
    for:
      seconds: 30
      milliseconds: 0
    to: cool
  - platform: time
    at: "16:00:00"
  - platform: state
    entity_id: climate.ice_bear
    to: auto
    for:
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: sensor.dryer
    to: "on"
    for:
      seconds: 30
      milliseconds: 0
  - platform: state
    to: "on"
    entity_id: sensor.washer
    for:
      seconds: 30
      milliseconds: 0
condition:
  - condition: state
    entity_id: binary_sensor.peak_usage
    state: "on"
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: climate.ice_bear
            for:
              hours: 0
              minutes: 0
              seconds: 30
            state: cool
        sequence:
          - service: notify.smartphones
            data:
              message: Ice Bear is cooling.
              title: ⚡Peak Usage Alert
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: climate.ice_bear
                state: auto
                for:
                  hours: 0
                  minutes: 0
                  seconds: 30
        sequence:
          - service: notify.smartphones
            data:
              message: Ice Bear is in ECO mode.
              title: ⚡Peak Usage Alert
      - conditions:
          - condition: state
            entity_id: sensor.washer
            state: "on"
            for:
              hours: 0
              minutes: 0
              seconds: 30
        sequence:
          - service: notify.smartphones
            data:
              title: ⚡Peak Usage Alert
              message: Washer is on.
      - conditions:
          - condition: state
            entity_id: sensor.dryer
            state: "on"
            for:
              hours: 0
              minutes: 0
              seconds: 30
        sequence:
          - service: notify.smartphones
            data:
              title: ⚡Peak Usage Alert
              message: Dryer is on.
    default: []
mode: single
