#################################################################
## Vacation Mode
#
## Telegram trigger for vacation mode to save energy.
#################################################################
id: "1668193814100"
alias: Vacation
description: Telegram trigger for vacation mode to save energy.
trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /leave
    id: telegram_leave
  - platform: event
    event_type: telegram_command
    event_data:
      command: /return
    id: telegram_return
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: telegram_leave
        sequence:
          - service: automation.turn_off
            data: {}
            target:
              entity_id:
                - automation.charge_toothbrushes
                - automation.climate_aqi
                - automation.climate_loft
                - automation.climate_purifier
                - automation.office_energy
                - automation.vacuum_schedule
            alias: Turn off automations.
          - service: fan.turn_off
            data: {}
            alias: Turn off fans.
            target:
              entity_id: fan.vacation_fans
          - service: switch.turn_off
            data: {}
            target:
              entity_id:
                - switch.vacation_plugs
            alias: Turn off plugs.
          - service: script.leave_vacuum
            data: {}
          - service: notify.telegram
            data:
              title: "\U0001F3DD Vacation: Start"
              message:
                Since you'll be out of town, I've taken the liberty of disabling
                some automations and turned off the fans to conserve power.
      - conditions:
          - condition: trigger
            id: telegram_return
        sequence:
          - service: automation.turn_on
            data: {}
            target:
              entity_id:
                - automation.charge_toothbrushes
                - automation.climate_aqi
                - automation.climate_loft
                - automation.climate_purifier
                - automation.office_energy
                - automation.vacuum_schedule
            alias: Turn on automations.
          - service: switch.turn_on
            data: {}
            alias: Turn on plugs.
            target:
              entity_id: switch.vacation_plugs
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.group_hallway
          - service: notify.telegram
            data:
              title: "\U0001F3E1 Vacation: End"
              message:
                Welcome home! I've taken the liberty of returning Farnsworth to
                his default state.
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.pinkie_lamp
    alias: Enable/Disable vacation mode.
mode: single
