#################################################################
## Volume Home
#
## Turn down volume of Google Home device at 10 pm.
#################################################################
id: 7011e9f1-4eb8-42c4-8253-ab40ada9e48c
alias: Volume
description: "Turn down volume of Google Home device at 10 pm."
trigger:
  - platform: time
    at: input_datetime.volume_morning
  - platform: time
    at: input_datetime.volume_night
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.volume_schedule
            state: "on"
        sequence:
          - service: media_player.volume_set
            target:
              entity_id:
                - media_player.loft_nest_hub
                - media_player.smart_clock
            data:
              volume_level: 0.5
          - service: media_player.volume_set
            target:
              entity_id:
                - media_player.bookshelf_speakers
                - media_player.upstairs_speakers
                - media_player.loft_bathroom
            data:
              volume_level: 0.3
          - service: notify.mobile_app_pixel_5
            data:
              message: Quiet time!
              title: 🤫 Farnsworth
    default:
      - service: media_player.volume_set
        target:
          entity_id:
            - media_player.loft_nest_hub
            - media_player.smart_clock
        data:
          volume_level: 0.6
      - service: media_player.volume_set
        data:
          volume_level: 0.4
        target:
          entity_id:
            - media_player.bookshelf_speakers
            - media_player.upstairs_speakers
            - media_player.loft_bathroom
      - service: notify.mobile_app_pixel_5
        data:
          title: 📢 Farnsworth
          message: I'm loud and proud, deal with it
mode: single
