#################################################################
## Volume Daytime
#
## Turn up volume of Google Home device at 9 am.
#################################################################
alias: Volume daytime
description: Turn up volume of Google Home device at 9 am.
trigger:
  - platform: time
    at: 09:00:00
condition: []
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.loft_clock
      volume_level: "0.60"
  - service: media_player.volume_set
    data:
      entity_id:
        - media_player.office_speaker
        - media_player.living_room_speaker
        - media_player.loft_bathroom
      volume_level: "0.40"
  - service: media_player.volume_set
    data:
      entity_id: media_player.loft_nest_hub
      volume_level: "0.60"
  - service: notify.telegram
    data:
      message: I'm loud and proud, deal with it.
      title: "📢 Farnsworth:"
mode: single
