#################################################################
## Switches for Heater.
#################################################################
# Heater switch with status
- platform: template
  switches:
    heat:
      unique_id: 8b0b1a49-4c2d-4b8f-86cd-af9569b6a1c4
      friendly_name: "Heat"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.switchbot_heat
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.switchbot_heat
      icon_template: >-
        {% if is_state('switch.heat', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}
