#################################################################
## Wake Steam Deck
#################################################################
- platform: wake_on_lan
  name: "Wake on Lan Deck"
  mac: !secret steam_mac
