#################################################################
## Tracker Primary
#
## Device tracker using Key Tile.
#################################################################
id: 531a7b42-9901-480d-bfa1-79969ae41289
alias: Tracker Secondary
description: "Device tracker using Key Tile."
trigger:
  - platform: state
    entity_id: sensor.beacon_tiffy_keys
  - platform: homeassistant
    event: start
condition: []
action:
  - service: device_tracker.see
    data:
      dev_id: her
      location_name: "{{iif(is_state('sensor.beacon_tiffy_keys', 'not_home'),
        states('device_tracker.tile_keys'), states('sensor.beacon_tiffy_keys'))}}"
      gps:
        - "{{ state_attr('device_tracker.tile_keys', 'latitude') }}"
        - "{{ state_attr('device_tracker.tile_keys', 'longitude') }}"
mode: queued
