#################################################################
## Vacuum Docked
#
## Notify Smartphones when Winston has returned to dock.
#################################################################
alias: Vacuum Docked
description: Notify Smartphones when Winston has returned to dock.
trigger:
  - platform: state
    entity_id: vacuum.winston
    from: returning
    to: docked
action:
  - service: notify.smartphones
    data:
      message: Happy to have been of service.
      title: "🤹🏻‍ Winston:"
mode: single
