#################################################################
## Vacuum Done
#
## Notify Smartphones when Winston has completed cleaning.
#################################################################
id: ed69a1d1-16be-45f2-9860-fb0f6d1b3e70
alias: Vacuum Done
description: Notify Smartphones when Winston has completed cleaning.
trigger:
  - platform: state
    entity_id: vacuum.winston
    from: cleaning
    to: returning
action:
  - service: notify.smartphones
    data:
      message: I've completed cleaning the residence. I'm off to retire. Cheerio!
      title: "🤹🏻‍ Winston:"
mode: single
