#################################################################
## Vacuum Schedule
#
## Clean at 11:00 pm.
#################################################################
id: 5e467d17-36b7-43ed-91af-264f783dfbba
alias: Vacuum Schedule
description: "Clean at 11:00 pm."
trigger:
  - platform: time
    at: input_datetime.clean_schedule
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: schedule.clean_partial
            state: "on"
          - condition: state
            entity_id: sensor.winston_clean_today
            state: "False"
        sequence:
          - service: vacuum.send_command
            data:
              command: app_segment_clean
              params:
                - 18
                - 20
            target:
              entity_id: vacuum.winston
          - service: vacuum.set_fan_speed
            data:
              fan_speed: Silent
            target:
              entity_id: vacuum.winston
      - conditions:
          - condition: state
            entity_id: schedule.clean_apt
            state: "on"
          - condition: state
            entity_id: sensor.winston_clean_today
            state: "False"
        sequence:
          - service: vacuum.send_command
            data:
              command: app_segment_clean
              params:
                - 16
                - 17
                - 18
                - 19
                - 20
            target:
              entity_id: vacuum.winston
          - service: vacuum.set_fan_speed
            data:
              fan_speed: Silent
            target:
              entity_id: vacuum.winston
    default: []
mode: single
