#################################################################
## Vacuum Clean
#
## Notify Smartphones when Winston starts cleaning.
#################################################################
id: e3dbf13f-880f-49dd-8257-3ae3932e42a1
alias: Vacuum Clean
description: Notify Smartphones when Winston starts cleaning.
trigger:
  - platform: state
    entity_id: vacuum.winston
    from: docked
    to: cleaning
action:
  - service: notify.smartphones
    data:
      message: Off to tidy up. Cheerio!
      title: "🤹🏻‍ Winston:"
mode: single
