backup:
  name: Backup
  description: Create a full or partial backup.
  fields:
    name:
      name: Name
      description: Backup Name.
      example: "Automatic Backup {{ now().strftime('%Y-%m-%d') }}"
      selector:
        text:
    include_addons:
      name: "Include: Add-ons"
      description: List of addons to backup (name or slug).
      example: "[grafana, Configurator, core_mariadb]"
      default: [grafana, Configurator, core_mariadb]
      selector:
        object:
    include_folders:
      name: "Include: Folders"
      description: List of folders to backup.
      example: "[homeassistant, Share, Local add-ons, ssl, media]"
      selector:
        select:
          multiple: true
          custom_value: true
          options:
            - label: Config
              value: config
            - label: Share
              value: share
            - label: SSL
              value: ssl
            - label: Media
              value: media
            - label: Local Add-ons
              value: addons
    exclude_addons:
      name: "Exclude: Add-ons"
      description: List of addons to backup (name or slug).
      example: "[grafana, Configurator, core_mariadb]"
      default: [grafana, Configurator, core_mariadb]
      selector:
        object:
    exclude_folders:
      name: "Exclude: Folders"
      description: List of folders to backup.
      example: "[homeassistant, Share, Local add-ons, ssl, media]"
      selector:
        select:
          multiple: true
          custom_value: true
          options:
            - label: Config
              value: config
            - label: Share
              value: share
            - label: SSL
              value: ssl
            - label: Media
              value: media
            - label: Local Add-ons
              value: addons
    password:
      name: Password
      description: Optional password to secure backup.
      example: "1234"
      selector:
        text:
          type: password
    keep_days:
      name: Keep days
      description: The number of days to keep the backup.
      example: "2"
      selector:
        number:
          min: 0
          max: 10000
          step: 0.01
          unit_of_measurement: days
          mode: box
    download_path:
      name: Download path
      description: Download the backup to a location after creation.
      example: /usb_drive
      advanced: true
      selector:
        text:

backup_full:
  name: Backup Full
  description: Create a full backup with optional exclusions.
  fields:
    name:
      name: Name
      description: Optional or it will be the current date and time.
      example: "Automatic Backup {{ now().strftime('%Y-%m-%d') }}"
      selector:
        text:
    password:
      name: Password
      description: Optional password to secure backup.
      example: "1234"
      selector:
        text:
          type: password
    keep_days:
      name: Keep days
      description: The number of days to keep the backup.
      example: "2"
      selector:
        number:
          min: 0
          max: 10000
          step: 0.01
          unit_of_measurement: days
          mode: box
    exclude:
      name: Exclude
      description: Addons/Folders to exclude from the backup.
      example: '{"addons": ["MariaDB"], "folders": ["Local add-ons", "share"]}'
      default: {"addons": ["MariaDB"], "folders": ["Local add-ons", "share"]}
      selector:
        object:
    download_path:
      name: Download path
      description: Download the backup to a location after creation.
      example: /usb_drive
      advanced: true
      selector:
        text:

backup_partial:
  name: Backup Partial
  description: Create a partial backup.
  fields:
    name:
      name: Name
      description: Backup Name.
      example: "Automatic Backup {{ now().strftime('%Y-%m-%d') }}"
      selector:
        text:
    addons:
      name: Add-ons
      description: List of addons to backup (name or slug).
      example: "[grafana, Configurator, core_mariadb]"
      default: [grafana, Configurator, core_mariadb]
      selector:
        object:
    folders:
      name: Folders
      description: List of folders to backup.
      example: "[homeassistant, Share, Local add-ons, ssl, media]"
      selector:
        select:
          multiple: true
          custom_value: true
          options:
            - label: Config
              value: config
            - label: Share
              value: share
            - label: SSL
              value: ssl
            - label: Media
              value: media
            - label: Local Add-ons
              value: addons
    password:
      name: Password
      description: Optional password to secure backup.
      example: "1234"
      selector:
        text:
          type: password
    keep_days:
      name: Keep days
      description: The number of days to keep the backup.
      example: "2"
      selector:
        number:
          min: 0
          max: 10000
          step: 0.01
          unit_of_measurement: days
          mode: box
    download_path:
      name: Download path
      description: Download the backup to a location after creation.
      example: /usb_drive
      advanced: true
      selector:
        text:

purge:
  name: Purge
  description: Purge expired backups.
