#################################################################
## Denon Volume Sensors
#################################################################
- platform: template
  sensors:
    denon_volume:
      value_template: >
       {% if is_state('media_player.dennis', 'on')  %}
          {% set n = states.media_player.dennis.attributes.volume_level | float %}
          {{ '%.1f'%( n*100.0) }}
        {% else %}
          "0"
        {% endif %} 
      friendly_name: Receiver Volume Level
      icon_template: mdi:volume-medium