#################################################################
## ESPresense Sensors
#################################################################
# Cube Keys Beacon
- platform: mqtt_room
  device_id: !secret beacon_cube_keys_id
  name: "Beacon Cube Keys "
  state_topic: !secret beacon_cube_keys_state_topic
  timeout: 60
  away_timeout: 120 # number of seconds after which the enitity will get status not_home
# Tiffy Keys Beacon
- platform: mqtt_room
  device_id: !secret beacon_tiffy_keys_id
  name: "Beacon Tiffy Keys "
  state_topic: !secret beacon_tiffy_keys_state_topic
  timeout: 60
  away_timeout: 120 # number of seconds after which the enitity will get status not_home
# Invisalign Case Beacon
- platform: mqtt_room
  device_id: !secret beacon_invisalign_case
  name: "Beacon Invisalign"
  state_topic: !secret beacon_invisalign_case_state_topic
  timeout: 60
  away_timeout: 120 # number of seconds after which the enitity will get status not_home
