#################################################################
## Nextbus Sensors
#################################################################
# 15 Bus
- platform: nextbus
  name: !secret name_15_inbound
  agency: !secret agency
  route: !secret route_15
  stop: !secret stop_15_inbound
- platform: nextbus
  name: !secret name_15_outbound
  agency: !secret agency
  route: !secret route_15
  stop: !secret stop_15_outbound
# Muni Metro T
- platform: nextbus
  name: !secret name_t_inbound
  agency: !secret agency
  route: !secret route_t
  stop: !secret stop_t_inbound
