#################################################################
## PC CPU Load Sensor
#################################################################
- platform: rest
  name: PC CPU Load
  resource: "http://192.168.86.29:9170/processes"
  headers:
    api-key: !secret pc_api_key
  value_template: "{{ value_json.load.currentLoad | round(0) }}"
  scan_interval: 10
  unit_of_measurement: "%"
#################################################################
## PC CPU Temp Sensor
#################################################################
- platform: rest
  name: PC CPU Temperature
  resource: "http://192.168.86.29:9170/cpu"
  headers:
    api-key: !secret pc_api_key
  value_template: "{{ value_json.temperature.main }}"
  scan_interval: 10
  unit_of_measurement: "ºC"
#################################################################
## PC GPU Temp Sensor
#################################################################
- platform: rest
  name: PC GPU Temperature
  resource: "http://192.168.86.29:9170/graphics"
  headers:
    api-key: !secret pc_api_key
  value_template: "{{ value_json.controllers.0.temperatureGpu }}"
  scan_interval: 10
  unit_of_measurement: "ºC"
#################################################################
## PC Release Sensor
#################################################################
- platform: rest
  name: PC Release
  resource: "http://192.168.86.29:9170/os"
  headers:
    api-key: !secret pc_api_key
  value_template: "{{ value_json.release }}"
  scan_interval: 10
