#################################################################
## Powercalc Sensors
#################################################################
- platform: powercalc
  entity_id: fan.kirby
  unique_id: 08459630-24bf-4c32-8cbe-bcb8ce852e43
  linear:
    calibrate:
      - 10 -> 3.55
      - 20 -> 4.25
      - 30 -> 5.50
      - 40 -> 7.35
      - 50 -> 10.20
      - 60 -> 16.00
      - 70 -> 20.00
      - 80 -> 30.20
      - 90 -> 41.50
      - 100 -> 54.00
  standby_power: 3.30
- platform: powercalc
  entity_id: fan.kitchen
  unique_id: eee91b1b-141f-4abe-95d7-abdb0d66a31a
  linear:
    calibrate:
      - 10 -> 5.35
      - 20 -> 6.05
      - 30 -> 7.30
      - 40 -> 9.25
      - 50 -> 12.00
      - 60 -> 17.90
      - 70 -> 21.80
      - 80 -> 32.10
      - 90 -> 43.40
      - 100 -> 55.80
  standby_power: 3.30
