#################################################################
## OS Release sensor.
#################################################################
- platform: scrape
  resource: "https://github.com/home-assistant/operating-system/releases/latest"
  select: "h1.d-inline.mr-3"
  name: OS Release
#################################################################
## Core Release sensor.
#################################################################
- platform: scrape
  resource: "https://github.com/home-assistant/core/releases/latest"
  select: "h1.d-inline.mr-3"
  name: Core Release
#################################################################
## Supervisor Release sensor.
#################################################################
- platform: scrape
  resource: "https://github.com/home-assistant/supervisor/releases/latest"
  select: "h1.d-inline.mr-3"
  name: Supervisor Release
#################################################################
## Mac Release sensor.
#################################################################
- platform: scrape
  resource: "https://github.com/home-assistant/iOS/releases/latest"
  select: "h1.d-inline.mr-3"
  name: Mac Release
