#################################################################
## Time sensor
#################################################################
- platform: time_date
  display_options:
    - "time"
    - "date"