#################################################################
## Vacuums sensors.
#################################################################
- platform: template
  sensors:
    vacuum_filter:
      friendly_name: Filter
      unit_of_measurement: " % "
      value_template: "{{ (states('sensor.winston_filter') | float / 5372 | round)}}"
    vacuum_mainbrush:
      friendly_name: Mainbrush    
      unit_of_measurement: " % "
      value_template:  "{{ (states('sensor.winston_main_brush') | float / 10680 | round)}}"
    vacuum_sensors:
      friendly_name: Sensors
      unit_of_measurement: " % "
      value_template: "{{ (states('sensor.winston_sensors') | float / 1073 | round)}}"
    vacuum_sidebrush:
      friendly_name: Sidebrush
      unit_of_measurement: " % "
      value_template: "{{ (states('sensor.winston_side_brush') | float / 7170 | round)}}"
