#################################################################
## Vacuums sensors.
#################################################################
- platform: template
  sensors:
    vacuum_filter:
      unique_id: 18a7147f-8cf7-4a8e-bbec-a2dc8b16443e
      friendly_name: Filter
      unit_of_measurement: " % "
      value_template: "{{ (states('sensor.winston_filter') | float / 5372 | round)}}"
    vacuum_mainbrush:
      unique_id: 1168bcd6-3a2b-4c7f-9bb1-3f6029efefb7
      friendly_name: Mainbrush
      unit_of_measurement: " % "
      value_template: "{{ (states('sensor.winston_main_brush') | float / 10680 | round)}}"
    vacuum_sensors:
      unique_id: 77fd9b65-6e37-41d4-ac1b-660291da824c
      friendly_name: Sensors
      unit_of_measurement: " % "
      value_template: "{{ (states('sensor.winston_sensors') | float / 1073 | round)}}"
    vacuum_sidebrush:
      unique_id: e30b897a-8063-4faf-87ac-be769f515135
      friendly_name: Sidebrush
      unit_of_measurement: " % "
      value_template: "{{ (states('sensor.winston_side_brush') | float / 7170 | round)}}"
