substitutions:
  name: "bluetooth-proxy-office"
  friendly_name: bluetooth-proxy-office
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: Bluetooth Proxy
api:
  encryption:
    key: gwWHbtbqxrqRQCd9a1rL2wxWCR2xy3OxWc2yk/smRWc=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
