substitutions:
  name: "m5stack-office"
  friendly_name: M5Stack Office
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret m5stack_office

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
