substitutions:
  name: "m5stack-loft"
  friendly_name: M5Stack Loft
packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret m5stack_loft


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
