#################################################################
## Powercalc Sensors
#################################################################
- platform: powercalc
  unique_id: 474eb1bc-b00d-4e33-8fc0-1e5ec78576d8
  name: Grid
  entity_id: sensor.dummy
  fixed:
    power: "{{(states('sensor.all_lights_power')|float + states('sensor.air_purifiers_power')|float + states('sensor.laundry_power')|float + states('sensor.dishwasher_plug_power')|float + states('sensor.workstation_plug_power')|float + states('sensor.refrigerator_power')|float + states('sensor.media_hub_power')|float)|round(3)}}"
