#################################################################
## Powercalc Sensors
#################################################################
# Laundry
- platform: powercalc
  create_group: Laundry
  unique_id: e18cad98-0485-4a9a-b759-add6b30c9806
  entities:
    # Washer
    - entity_id: switch.washer_power
      unique_id: 38b4cfeb-ca7a-4450-90a7-03e66897e7a2
      fixed:
        power: 200
    # Dryer
    - entity_id: switch.dryer_power
      unique_id: 75dcb721-9a77-4a5b-9066-7144d86ecad6
      fixed:
        power: 2000
