#################################################################
## Media Powercalc Sensors
#################################################################
# Media group
- platform: powercalc
  create_group: Media Hub
  unique_id: 03ef1af0-c214-4d07-9b3a-c9bc5f4030bd
  entities:
    - entity_id: media_player.shield_tv
      unique_id: fdde983a-6dfa-43e4-8386-18ceeb02da1c
      fixed:
        power: 4.15
        states_power:
          media_content_id|Amazon: 7.50
          media_content_id|HBO: 15.50
          media_content_id|Hulu: 15.50
          media_content_id|Netflix: 15.50
      standby_power: 3.55
    # Kitchen Dyson
    # - entity_id: fan.kitchen
    #   unique_id: eee91b1b-141f-4abe-95d7-abdb0d66a31a
    #   name: Dyson Kitchen
    #   linear:
    #     calibrate:
    #       - 10 -> 5.35
    #       - 20 -> 6.05
    #       - 30 -> 7.30
    #       - 40 -> 9.25
    #       - 50 -> 12.00
    #       - 60 -> 17.90
    #       - 70 -> 21.80
    #       - 80 -> 32.10
    #       - 90 -> 43.40
    #       - 100 -> 55.80
    #   standby_power: 3.30
    # # Airmega
    # - entity_id: fan.airmega
    #   unique_id: bd765aa9-bf75-452b-b034-1e35c5ade61c
    #   name: Airmega
    #   linear:
    #     calibrate:
    #       - 0 -> 6.05
    #       - 33 -> 8.36
    #       - 66 -> 26.20
    #       - 100 -> 61.60
