#################################################################
## Media Powercalc Sensors
#################################################################
# Media group
- platform: powercalc
  create_group: Media Hub
  unique_id: 03ef1af0-c214-4d07-9b3a-c9bc5f4030bd
  entities:
    - entity_id: media_player.shield_tv
      unique_id: fdde983a-6dfa-43e4-8386-18ceeb02da1c
      fixed:
        power: 4.15
        states_power:
          app_id|com.disney.disneyplus: 6.75
          app_id|com.hbo.hbonow: 15.50
          app_id|com.hulu.livingroomplus: 15.50
          app_id|com.netflix.ninja: 15.50
          app_id|com.plexapp.android: 5.75
          app_id|com.amazon.amazonvideo.livingroom: 7.50
          app_id"|com.google.android.youtube.tv: 12.50
      standby_power: 3.55
    # Television
    - entity_id: media_player.sony_bravia_tv
      unique_id: 992e685e-cc2a-48b0-bec7-4812d72e7e39
      fixed:
        power: 85.50
      standby_power: 13.50
    # Denon Receiver
    - entity_id: media_player.dennis
      power_sensor_id: sensor.dennis_plug_power
    # Coax Extender
    - entity_id: sensor.dummy
      unique_id: 57b5132b-8cb0-440f-a66b-bdd20a6481ea
      name: Coax Extender
      fixed:
        power: 1.85
    # Hue Bridge
    - entity_id: sensor.dummy
      unique_id: a478557e-e08a-428c-8c25-f771dc81372a
      name: Hue Bridge
      fixed:
        power: 1.30
    # Raspberry Pi
    - entity_id: sensor.dummy
      unique_id: bcb0dce8-0d8b-4f5a-aec8-8b00d36b5f96
      name: Raspberry Pi
      fixed:
        power: 2.85
    # Switch
    - entity_id: sensor.dummy
      unique_id: 8b14886a-ccf7-4f67-ae12-5bb872a20625
      name: Switch
      fixed:
        power: 2.30
